// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-rSgt1SauyJ6DGGuXAv71HrjsrX7YI7A',
    appId: '1:234647187369:web:1c42b909092f225964deb8',
    messagingSenderId: '234647187369',
    projectId: 'feedback-c0df2',
    authDomain: 'feedback-c0df2.firebaseapp.com',
    storageBucket: 'feedback-c0df2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA275xD3fe-13trd92K88UJu01faTEAKtI',
    appId: '1:234647187369:android:0a05e1078e8438e964deb8',
    messagingSenderId: '234647187369',
    projectId: 'feedback-c0df2',
    storageBucket: 'feedback-c0df2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyckHM0omYzBpRd-yOuxwmpe4TzKNCru4',
    appId: '1:234647187369:ios:0bc97b4356354d9864deb8',
    messagingSenderId: '234647187369',
    projectId: 'feedback-c0df2',
    storageBucket: 'feedback-c0df2.appspot.com',
    iosBundleId: 'com.example.feedback',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyckHM0omYzBpRd-yOuxwmpe4TzKNCru4',
    appId: '1:234647187369:ios:f2240f7bd61fbee564deb8',
    messagingSenderId: '234647187369',
    projectId: 'feedback-c0df2',
    storageBucket: 'feedback-c0df2.appspot.com',
    iosBundleId: 'com.example.feedback.RunnerTests',
  );
}
